<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Senior" failures="1" tests="3" name="Test1" time="8.448" errors="0" timestamp="2025-02-28T18:45:08 EET">
  <testcase classname="Tests.LoginTest" name="testLoginLogout" time="1.654"/>
  <testcase classname="Tests.LoginTest" name="title" time="0.031"/>
  <testcase classname="Tests.LoginTest" name="Welcome_to_Secure_Area" time="0.025">
    <failure type="java.lang.AssertionError" message="Subheader message is incorrect! expected [Welcome to the Secure Area. When you are done click logout below.] but found [This is where you can log into the secure area. Enter tomsmith for the username and SuperSecretPassword! for the password. If the information is wrong you should see error messages.]">
      <![CDATA[java.lang.AssertionError: Subheader message is incorrect! expected [Welcome to the Secure Area. When you are done click logout below.] but found [This is where you can log into the secure area. Enter tomsmith for the username and SuperSecretPassword! for the password. If the information is wrong you should see error messages.]
at Tests.LoginTest.Welcome_to_Secure_Area(LoginTest.java:54)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Welcome_to_Secure_Area -->
</testsuite> <!-- Test1 -->
